# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-02 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserExtension',
            new_name='Collab',
        ),
    ]
